### ISSUE TITLE
Inconsistencies between feedback file and graded file.

### ISSUE THREAD

**Issue by Lourenzutti** [UBC-DSCI/rudaux#115] opened 2021-04-13 22:58 UTC
There are some inconsistencies between the file used for grading and the file the students received the feedback. I am not sure why. I will investigate this later on. 

But maybe we could add support for forcing rudaux to re-run and re-return the feedback?

**Comment by trevorcampbell** [comment] 2021-04-13 22:59
Can you provide more details please? Maybe an example of what you're seeing would be helpful, especially if we only return to this a few months from now.

**Comment by Lourenzutti** [comment] 2021-04-14 06:02
Sure thing! Here's a screenshot.
On the right is the student's feedback on the left what is appearing for us on nbgrader.  

![image](https://user-images.githubusercontent.com/5846205/114661639-2ab8e380-9cac-11eb-9017-5522db4691a5.png)

**Comment by trevorcampbell** [comment] 2021-04-14 06:11
Weird -- was this an assignment where rudaux ran with no issues, or was this one where you had to go in and manually modify the workflow?

**Comment by Lourenzutti** [comment] 2021-04-14 06:37
That's a great question! 
I don't think I modified the workflow in this case, but I am not 100% sure.

**Comment by trevorcampbell** [comment] 2021-09-21 19:34
I can't reproduce this myself, so I'll close it for now. If it happens again we can re-open.

> But maybe we could add support for forcing rudaux to re-run and re-return the feedback?

The new upcoming version of rudaux is going to use make-like tasks that rerun things when upstream files are newer than downstream. So this should be handled.

**Closed by trevorcampbell** 2021-09-21 19:34 UTC
